### ISSUE TITLE
Python 3.10.8 运行报错 ImportError: cannot import name 'batched' from 'itertools' (unknown location)

### ISSUE THREAD

**Issue by Nicksxs** [iiicebearrr/spiders-for-all#8]
在 python 3.10.8 下
运行 
```shell
python -m spiders_for_all run-spider -n author -p mid xxx
```
报错 ImportError: cannot import name 'batched' from 'itertools' (unknown location)

**Comment by Nicksxs** [comment]
升到 12 又有个问题
  File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/__main__.py", line 53, in run_spider
    spider = SPIDERS[name](**{k: v for k, v in params})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/spiders.py", line 594, in __init__
    else min(total, self.get_total(self.mid))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by iiicebearrr** [comment]
> 升到 12 又有个问题 File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/**main**.py", line 53, in run_spider spider = SPIDERS[name](**{k: v for k, v in params}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/spiders.py", line 594, in **init** else min(total, self.get_total(self.mid)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '<' not supported between instances of 'int' and 'str'

从命令行去掉`total`参数可以暂时解决这个问题, 我稍后会发布一个新的版本来修复这个问题

**Comment by iiicebearrr** [comment]
> 升到 12 又有个问题 File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/**main**.py", line 53, in run_spider spider = SPIDERS[name](**{k: v for k, v in params}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/spiders.py", line 594, in **init** else min(total, self.get_total(self.mid)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '<' not supported between instances of 'int' and 'str'

`total`参数的问题已经修复了, 现在你可以通过`pip install spiders_for_all --upgrade`来更新你的版本

**Comment by Nicksxs** [comment]
> > 升到 12 又有个问题 File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/**main**.py", line 53, in run_spider spider = SPIDERS[name](**{k: v for k, v in params}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/name/.pyenv/versions/3.12.0/lib/python3.12/site-packages/spiders_for_all/bilibili/spiders.py", line 594, in **init** else min(total, self.get_total(self.mid)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: '<' not supported between instances of 'int' and 'str'
> 
> `total`参数的问题已经修复了, 现在你可以通过`pip install spiders_for_all --upgrade`来更新你的版本

刚找到，想帮你修来着，感谢

**Comment by iiicebearrr** [comment]
考虑到兼容以及维护问题，3.12之前的版本将不考虑支持计划
